### PR TITLE
move to exception parsing

### PR DESCRIPTION
**Pull request by SimonCropp**
@matkoch  i made the stack trace parsable, and shipped a nuget for the parsing. but when running it failes to load the assembly. can u take a look?

### CODE REVIEW

**Comment by SimonCropp** [comment]
@matkoch ok i tested this by manually copying Verify.ExceptionParsing.dll into the plugin dir and it worked. so all this needs is some extra code to bundle Verify.ExceptionParsing.dll into the rider plugin

**Comment by SimonCropp** [comment]
ok solved the bundling

**Comment by matkoch** [comment]
@SimonCropp I made some changes:

- Showing a user-visible error dialog. Exceptions can be seen in EAP builds or when internal mode is on, but otherwise, it will show nothing.
- Inlined some methods for educational purpose

If you're good, I can release it like this.

**Comment by SimonCropp** [comment]
yep all good here

**Pull request merged**
